In [ ]:
"""
    TARGETS:
    - Predict deaths / new infections
    - Predict who can spread to who
"""

In [81]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import date, datetime
import math
import seaborn as sns

%matplotlib inline
sns.set(rc={'figure.figsize':(80,40)})

In [149]:
p_info = pd.read_csv("./korea_dataset/PatientInfo.csv")
p_route = pd.read_csv("./korea_dataset/PatientRoute.csv")

In [160]:
p_info.head(20)

,patient_id,sex,birth_year,age,country,province,city,disease,infection_case,confirmed_date,released_date,state
0,1000000001,0,1964.0,56,0,0,0,1.0,0,1/23/20,2/05/20,0
1,1000000002,0,1987.0,33,0,0,1,1.0,0,1/30/20,3/02/20,0
2,1000000003,0,1964.0,56,0,0,2,1.0,1,1/30/20,2/19/20,0
3,1000000004,0,1991.0,29,0,0,3,1.0,0,1/30/20,2/15/20,0
4,1000000005,1,1992.0,28,0,0,4,1.0,1,1/31/20,2/24/20,0
5,1000000006,1,1966.0,54,0,0,2,1.0,1,1/31/20,2/19/20,0
6,1000000007,0,1995.0,25,0,0,2,1.0,1,1/31/20,2/10/20,0
7,1000000008,0,1992.0,28,0,0,5,1.0,0,2/02/20,2/24/20,0
8,1000000009,0,1983.0,37,0,0,6,1.0,0,2/05/20,2/21/20,0
9,1000000010,1,1960.0,60,0,0,4,1.0,1,2/05/20,2/29/20,0
10,1000000011,1,1962.0,58,1,0,7,1.0,0,2/06/20,2/29/20,0
11,1000000012,0,1992.0,28,0,0,5,1.0,0,2/07/20,2/27/20,0
12,1000000013,0,1938.0,82,0,0,2,1.0,1,2/16/20,04/23/20,0
13,1000000014,1,1952.0,68,0,0,2,1.0,1,2/16/20,3/12/20,0
14,1000000015,0,1943.0,77,0,0,8,1.0,2,2/19/20,04/23/20,1
15,1000000016,0,1945.0,75,0,0,2,1.0,1,2/19/20,3/11/20,0
16,1000000017,0,1944.0,76,0,0,2,1.0,1,2/20/20,3/01/20,0
17,1000000018,0,2000.0,20,0,0,5,1.0,3,2/20/20,04/23/20,1
18,1000000019,1,1941.0,79,0,0,2,1.0,1,2/20/20,3/08/20,0
19,1000000020,1,1944.0,76,0,0,8,1.0,2,2/20/20,04/23/20,1

In [151]:
#confirm_g = p_info["confirmed_date"].value_counts().rename_axis("date").reset_index(name="No. of occurances")

#release_g = p_info["released_date"].fillna(date.today().strftime("%m/%d/%Y"), inplace=True)
#release_g = p_info["released_date"].value_counts().rename_axis("date").reset_index(name="No. of occurances")
#p_info["deceased_date"].isnull().sum()  
#2682/ 3128 -> 86%
#print(len(p_info["infected_by"]))

In [152]:
infected_by = p_info["infected_by"].ravel()
contact_number = p_info["contact_number"].ravel()
deceased_date = p_info["deceased_date"].ravel()
patient_id = p_info["patient_id"].ravel()

In [153]:
p_info.drop("global_num", axis=1, inplace=True)
p_info.drop("infection_order", axis=1, inplace=True)
p_info.drop("symptom_onset_date", axis=1, inplace=True)
p_info.drop("infected_by", axis=1, inplace=True)
p_info.drop("contact_number", axis=1, inplace=True)
p_info.drop("deceased_date", axis=1, inplace=True)

In [154]:
d_disease = {"TRUE": 0, "FALSE": 1}
d_gender = {"male": 0, "female": 1, "n/a": 2}
d_state = {"released": 0, "isolated": 1, "deceased": 2}

p_info["disease"].fillna("FALSE", inplace=True)
p_info["disease"] = p_info["disease"].map(d_disease)

p_info["sex"].fillna("n/a", inplace=True)
p_info["sex"] = p_info["sex"].map(d_gender)

p_info["state"] = p_info["state"].map(d_state)

p_info["released_date"].fillna(date.today().strftime("%m/%d/%y"), inplace=True)
#p_info["released_date"].fillna(0, inplace=True)

In [155]:
d_infection_case = {}

infection_case_counter = 0
p_info["infection_case"].fillna("etc", inplace=True)

for case in p_info["infection_case"]:
    if case not in d_infection_case:
        d_infection_case[str(case)] = infection_case_counter
        infection_case_counter += 1

p_info["infection_case"] = p_info["infection_case"].map(d_infection_case)

In [156]:
d_city = {}

# TODO: Modify - add props. -gu, -gun, -si with regex

city_counter = 0
p_info["city"].fillna("etc", inplace=True)

for city in p_info["city"]:
    if city not in d_city:
        d_city[str(city)] = city_counter
        city_counter += 1

#p_info["city"].unique()
#p_info["city"].isnull().values.any()
p_info["city"] = p_info["city"].map(d_city)

In [157]:
d_province = {}

# TODO: Modify - add props. Special City / Metropolitan City / Province(-do) with regex

province_counter = 0

for province in p_info["province"]:
    if province not in d_province:
        d_province[str(province)] = province_counter
        province_counter += 1

p_info["province"] = p_info["province"].map(d_province)

In [158]:
d_country = {}

country_counter = 0
p_info["country"].fillna("etc", inplace=True)

for country in p_info["country"]:
    if country not in d_country:
        d_country[str(country)] = country_counter
        country_counter += 1

p_info["country"] = p_info["country"].map(d_country)

In [159]:
year = date.today().year
for count, age in enumerate(p_info["age"], 0):
    try:
        n_age = int(year-int(p_info["birth_year"][count]))
        p_info.at[count, "age"] = n_age
    except:
        continue

c_patient_info = p_info[p_info["age"].notnull()]
c_patient_info = p_info[p_info["birth_year"].notnull()]

a_avg = c_patient_info["age"].values.mean()
p_info["age"].fillna(a_avg, inplace=True)

b_avg = c_patient_info["birth_year"].values.mean()
p_info["birth_year"].fillna(b_avg, inplace=True)